In [1]:
from MLP import MLP
from MLPRegression import MLPRegression
import numpy as np
import pandas as pd

x = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]])
nor_y = np.array([[0], [1], [1], [1], [1], [1], [1], [1]])
nand_y = np.array([[1], [0], [0], [0], [0], [0], [0], [0]])
x_regression = np.array([[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]])
y_regression = np.array([[9], [10], [19], [21], [22], [25], [39], [40], [41], [47]])

# Trabalho 8 – N1

## 1 - Implemente uma RNA MLP com treinamento backpropagation para resolução do problema de classificação da porta NAND com 3 entradas? PS: Use a função de ativação sigmoide.

In [2]:
mlp_nand = MLP(activation_function='sigmoid')
mlp_nand.fit(x, nand_y)
mlp_nand.predict([1, 1, 1])

0

In [3]:
mlp_nand.predict([0, 1, 1])

0

In [4]:
mlp_nand.predict([1, 0, 0])

0

In [5]:
mlp_nand.predict([0, 0, 0])

1

## 2 - Implemente uma RNA MLP com treinamento backpropagation para resolução do problema de classificação da porta NOR com 3 entradas? PS: Use a função de ativação tangente hiperbólica.

In [2]:
mlp_nor = MLP()
mlp_nor.fit(x, nor_y)
mlp_nor.predict([1, 1, 1])

1

In [3]:
mlp_nor.predict([0, 1, 1])

1

In [4]:
mlp_nor.predict([1, 0, 0])

1

In [5]:
mlp_nor.predict([0, 0, 0])

0

## 3 - Implemente uma RNA MLP com treinamento backpropagation com as seguintes entradas e saídas do problema de regressão abaixo? PS: Use a função de ativação sigmoide.
## Entradas: [0; 1; 2; 3; 4; 5; 6; 7; 8; 9].
## Saídas: [9; 10; 19; 21; 22; 25; 39; 40; 41; 47].

In [31]:
mlp_regr_sigmoid = MLPRegression(hidden_layer_neurons=30, learning_rate=0.0001, activation_function='sigmoid')
mlp_regr_sigmoid.fit(x_regression, y_regression)
mlp_regr_sigmoid.predict(x_regression)

array([[ 6.88723181],
       [12.1536906 ],
       [17.29392943],
       [22.19489758],
       [26.76623043],
       [30.94478003],
       [34.69486616],
       [38.00555124],
       [40.88613337],
       [43.36087822]])

In [32]:
mlp_regr_sigmoid.predict([[10]])

array([[45.46382235]])

## 4 - Repita o passo da “questão 3” com a função de ativação tangente hiperbólica?

In [33]:
mlp_regr_tangent = MLPRegression(number_of_epochs=1000, hidden_layer_neurons=100, learning_rate=0.00001)
mlp_regr_tangent.fit(x_regression, y_regression)
mlp_regr_tangent.predict(x_regression)

array([[ 0.        ],
       [15.92273766],
       [24.29423845],
       [28.66589175],
       [31.37439841],
       [33.23533912],
       [34.58072329],
       [35.57961943],
       [36.3326418 ],
       [36.90558199]])